# Generated by Django 2.1.2 on 2018-10-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181024_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captcha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CAPTCHA', models.TextField(blank=True, default='6LcR1XYUAAAAAKgKVOvGrpPUvqka_4kP7ZkjEgj9')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='CAPTCHA',
        ),
    ]
