# Generated by Django 2.1.2 on 2018-10-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181025_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='images/media/'),
        ),
    ]
