# Generated by Django 2.1.2 on 2018-10-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181029_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
